mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/andes-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/cocacola-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/crayola-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/folgers-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/heineken-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/hunts-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/kellogg-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/kleenex-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/kotex-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/libava-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/macadamia-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/milo-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/mm-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/pocky-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/raisins-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/stax-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/swissmiss-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/vanish-l/* ~/pycococreator/examples/shapes/all-annotation
mv  -v ~/pycococreator/examples/shapes/all-annotation/train_labels/viva-l/* ~/pycococreator/examples/shapes/all-annotation

