mv  -v ~/pycococreator/examples/shapes/all/train_images/andes/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/cocacola/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/crayola/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/folgers/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/heineken/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/hunts/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/kellogg/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/kleenex/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/kotex/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/libava/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/macadamia/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/milo/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/mm/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/pocky/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/raisins/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/stax/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/swissmiss/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/vanish/* ~/pycococreator/examples/shapes/all
mv  -v ~/pycococreator/examples/shapes/all/train_images/viva/* ~/pycococreator/examples/shapes/all

